/**
 * Deck EA (Exchange Allowance) Tallies
 *
 * Pure counters behind the deck status readout: affinity EA generated by the
 * deployed identities' skills against the EA their equipped EGOs consume, and
 * status effect keyword counts split between the deployed roster and the full
 * one (deployed plus backups).
 */

import {
  AFFINITIES,
  DEFAULT_SKILL_EA,
  OFFENSIVE_SKILL_SLOTS,
  STATUS_EFFECTS,
} from '@/shared/gameData'
import type { AffinityCount, DeckState, KeywordCount } from '../types/DeckTypes'

/**
 * Identity spec fields the EA tallies read
 */
export interface IdentityEASpec {
  attributeType?: readonly string[]
  skillKeywordList?: readonly string[]
}

/**
 * EGO spec fields the EA tallies read
 */
export interface EGOEASpec {
  requirements?: Readonly<Record<string, number>>
}

/**
 * Keyword tally per roster scope; `count` mirrors `allCount`
 */
export type KeywordEACount = KeywordCount & {
  deployedCount: number
  allCount: number
}

/** Deployment order holds 0-based sinner indices; equipment is keyed 1-based */
function sinnerCodesOf(deploymentOrder: readonly number[]): string[] {
  return deploymentOrder.map((index) => String(index + 1))
}

/**
 * Tallies affinity EA generated by identity skills against the EA consumed by
 * equipped EGOs, across every sinner in the deployment order (backups included)
 *
 * Generation weights each offensive skill slot by its default EA (S1=3, S2=2,
 * S3=1); consumption sums the requirements of every equipped EGO. Neither side
 * is clamped, so consumption may exceed generation.
 *
 * @param deckState - Deck equipment and deployment order
 * @param identitySpec - Identity spec map keyed by identity ID
 * @param egoSpec - EGO spec map keyed by EGO ID
 * @returns One entry per affinity, in AFFINITIES order
 */
export function computeAffinityEA(
  deckState: DeckState,
  identitySpec: Record<string, IdentityEASpec>,
  egoSpec: Record<string, EGOEASpec>,
): AffinityCount[] {
  const counts: Record<string, { generated: number; consumed: number }> = {}
  AFFINITIES.forEach((affinity) => {
    counts[affinity] = { generated: 0, consumed: 0 }
  })

  sinnerCodesOf(deckState.deploymentOrder).forEach((sinnerCode) => {
    const equipment = deckState.equipment[sinnerCode]
    if (!equipment) return

    const attributeType = identitySpec[equipment.identity.id]?.attributeType
    OFFENSIVE_SKILL_SLOTS.forEach((slot) => {
      const affinity = attributeType?.[slot]
      if (affinity === undefined) return

      const entry = counts[affinity]
      if (entry) entry.generated += DEFAULT_SKILL_EA[slot]
    })

    Object.values(equipment.egos).forEach((equippedEgo) => {
      if (!equippedEgo) return

      const requirements = egoSpec[equippedEgo.id]?.requirements
      if (!requirements) return

      Object.entries(requirements).forEach(([affinity, cost]) => {
        const entry = counts[affinity]
        if (entry && cost > 0) entry.consumed += cost
      })
    })
  })

  return AFFINITIES.map((affinity) => ({
    affinity,
    generated: counts[affinity].generated,
    consumed: counts[affinity].consumed,
  }))
}

/**
 * Tallies status effect keywords from identity skill keyword lists, once for
 * the deployed roster and once for the full one
 *
 * @param deckState - Deck equipment, deployment order and deployment config
 * @param identitySpec - Identity spec map keyed by identity ID
 * @returns One entry per status effect, in STATUS_EFFECTS order
 */
export function computeKeywordEA(
  deckState: DeckState,
  identitySpec: Record<string, IdentityEASpec>,
): KeywordEACount[] {
  const deployedCounts: Record<string, number> = {}
  const allCounts: Record<string, number> = {}
  STATUS_EFFECTS.forEach((effect) => {
    deployedCounts[effect] = 0
    allCounts[effect] = 0
  })

  const tally = (sinnerCodes: string[], into: Record<string, number>) => {
    sinnerCodes.forEach((sinnerCode) => {
      const equipment = deckState.equipment[sinnerCode]
      if (!equipment) return

      identitySpec[equipment.identity.id]?.skillKeywordList?.forEach((keyword) => {
        if (into[keyword] !== undefined) into[keyword] += 1
      })
    })
  }

  const allSinnerCodes = sinnerCodesOf(deckState.deploymentOrder)
  tally(allSinnerCodes.slice(0, deckState.deploymentConfig.maxDeployed), deployedCounts)
  tally(allSinnerCodes, allCounts)

  return STATUS_EFFECTS.map((keyword) => ({
    keyword,
    count: allCounts[keyword],
    deployedCount: deployedCounts[keyword],
    allCount: allCounts[keyword],
  }))
}
