apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - spring-daemonset.yaml
  - spring-service.yaml
  - traefik-controller.yaml
  - traefik-gateway.yaml
  - external-secret.yaml
  - jwt-secrets.yaml
  - origin-tls-secrets.yaml
  - runtime-config.yaml
  - redis-auth.yaml
  - redis-ratelimit.yaml
  - prometheus.yaml
  - kube-state-metrics.yaml
