apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - spring-daemonset.yaml
  - spring-service.yaml
  - traefik-controller.yaml
  - traefik-gateway.yaml
  - external-secret.yaml
  - jwt-secrets.yaml
  - grafana-remote-write-secret.yaml
  - origin-tls-secrets.yaml
  - runtime-config.yaml
  - redis-auth.yaml
  - redis-ratelimit.yaml
  - prometheus.yaml
  - kube-state-metrics.yaml
  - mysqld-exporter.yaml
  - redis-exporter.yaml
  - alloy-logs.yaml
  - node-exporter.yaml

configMapGenerator:
  - name: mysqld-tls-cnf
    files:
      - mysqld-tls.cnf
  - name: rds-ca-bundle
    files:
      - rds-global-bundle.pem
