#!/usr/bin/env python3
"""
Korean font coverage generator.

KOTRA Bold and S-Core Dream map all 11,172 modern Hangul syllables in their
`cmap` but only supply real outlines for the common KS X 1001 set (~2,350).
The rest are mapped to EMPTY glyphs. A blank-but-mapped glyph defeats the
browser's per-glyph font fallback: the font "wins" the codepoint and renders
nothing instead of falling through to the complete Pretendard fallback.

The fonts cannot be altered, so we constrain them in CSS instead. This script
inspects each binary, finds the codepoints with real (non-empty) outlines, and
writes those as a `unicode-range` allowlist on each `@font-face`. Codepoints
outside the allowlist (the blank Hangul) are treated by the browser as not
covered, so fallback to Pretendard resumes.

The binaries are immutable, so this runs once and the output is committed.
Re-run only if a font file is replaced.

    python3 frontend/scripts/gen-korean-font-coverage.py
"""

from __future__ import annotations

from pathlib import Path

from fontTools.ttLib import TTFont

REPO = Path(__file__).resolve().parents[2]
FONT_DIR = REPO / "frontend/src/assets/fonts"
OUT = REPO / "frontend/src/styles/korean-font-coverage.css"

# Each face mirrors the original @font-face that lived in globals.css, plus the
# generated unicode-range. `src` is the CSS value relative to the OUT file.
FACES = [
    {
        "family": "KOTRA_BOLD",
        "file": "KOTRA_BOLD.ttf",
        "src": "url('../assets/fonts/KOTRA_BOLD.ttf')",
        "weight": "700",
        "comment": "KOTRA Bold - Korean display font",
    },
    {
        "family": "S-Core Dream",
        "file": "S-Core_Dream_OTF/SCDream5.otf",
        "src": "url('../assets/fonts/S-Core_Dream_OTF/SCDream5.otf') format('opentype')",
        "weight": "500",
        "comment": "S-Core Dream Medium - Korean body font",
    },
]


def real_codepoints(font_path: Path) -> set[int]:
    """Codepoints whose mapped glyph has a real (non-empty) outline.

    A composite TrueType glyph reports a negative contour count and is real;
    only an exactly-zero contour count (or an empty CFF charstring) is blank.
    """
    font = TTFont(font_path, fontNumber=0, lazy=True)
    cmap = font.getBestCmap()
    glyf = font.get("glyf")
    charstrings = None
    if glyf is None:
        cff = font["CFF "].cff
        charstrings = cff[cff.fontNames[0]].CharStrings

    real: set[int] = set()
    for cp, glyph_name in cmap.items():
        if glyf is not None:
            blank = glyf[glyph_name].numberOfContours == 0
        else:
            blank = charstrings[glyph_name].calcBounds(charstrings) is None
        if not blank:
            real.add(cp)
    return real


def to_ranges(codepoints: set[int]) -> list[tuple[int, int]]:
    """Collapse a codepoint set into sorted inclusive [start, end] runs."""
    ordered = sorted(codepoints)
    ranges: list[tuple[int, int]] = []
    start = prev = ordered[0]
    for cp in ordered[1:]:
        if cp == prev + 1:
            prev = cp
        else:
            ranges.append((start, prev))
            start = prev = cp
    ranges.append((start, prev))
    return ranges


def format_unicode_range(ranges: list[tuple[int, int]]) -> str:
    return ", ".join(
        f"U+{a:X}" if a == b else f"U+{a:X}-{b:X}" for a, b in ranges
    )


def build_face(face: dict) -> str:
    real = real_codepoints(FONT_DIR / face["file"])
    ranges = to_ranges(real)
    return (
        f"/* {face['comment']} - unicode-range = real-outline codepoints only */\n"
        f"@font-face {{\n"
        f"  font-family: '{face['family']}';\n"
        f"  src: {face['src']};\n"
        f"  font-weight: {face['weight']};\n"
        f"  font-style: normal;\n"
        f"  font-display: swap;\n"
        f"  unicode-range: {format_unicode_range(ranges)};\n"
        f"}}\n"
    )


def main() -> None:
    header = (
        "/*\n"
        " * GENERATED by frontend/scripts/gen-korean-font-coverage.py - do not edit by hand.\n"
        " *\n"
        " * KOTRA Bold and S-Core Dream map every modern Hangul syllable in their cmap\n"
        " * but only outline the common KS X 1001 set; the rest are blank glyphs that\n"
        " * block fallback. The unicode-range below restricts each face to codepoints it\n"
        " * actually renders, so uncovered syllables fall through to Pretendard.\n"
        " */\n\n"
    )
    body = "\n".join(build_face(face) for face in FACES)
    OUT.write_text(header + body, encoding="utf-8")

    # Sanity check: a blank syllable must be excluded, a common one included.
    scd = real_codepoints(FONT_DIR / "S-Core_Dream_OTF/SCDream5.otf")
    assert 0xD137 not in scd, "U+D137 should be blank in S-Core"
    assert 0xAC00 in scd, "U+AC00 (가) should be real in S-Core"
    print(f"Wrote {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
