apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy-logs
spec:
  template:
    spec:
      containers:
        - name: alloy
          env:
            - name: CLUSTER_NAME
              value: oregon
