apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld-exporter
spec:
  template:
    spec:
      containers:
        - name: mysqld-exporter
          env:
            - name: MYSQLD_ADDRESS
              value: mysql-replica.seoul.danteplanner.internal:3306
