package org.danteplanner.backend.planner.validation;

public enum ErrorCode {
    EMPTY_CONTENT("EMPTY_CONTENT"),
    SIZE_EXCEEDED("SIZE_EXCEEDED"),
    MALFORMED_JSON("MALFORMED_JSON"),
    MISSING_REQUIRED_FIELD("MISSING_REQUIRED_FIELD"),
    UNKNOWN_FIELD("UNKNOWN_FIELD"),
    INVALID_CATEGORY("INVALID_CATEGORY"),
    INVALID_FIELD_TYPE("INVALID_FIELD_TYPE"),
    INVALID_ID_REFERENCE("INVALID_ID_REFERENCE"),
    VALUE_OUT_OF_RANGE("VALUE_OUT_OF_RANGE"),
    DUPLICATE_VALUE("DUPLICATE_VALUE"),
    INVALID_SEQUENCE("INVALID_SEQUENCE"),
    GIFT_NOT_AFFORDABLE("GIFT_NOT_AFFORDABLE"),
    UNKNOWN_CONTENT_VERSION("UNKNOWN_CONTENT_VERSION"),
    IDENTITY_UNKNOWN_ID("IDENTITY_UNKNOWN_ID"),
    EGO_UNKNOWN_ID("EGO_UNKNOWN_ID"),
    GIFT_UNKNOWN_ID("GIFT_UNKNOWN_ID"),
    FLOOR_UNKNOWN_GIFT_ID("FLOOR_UNKNOWN_GIFT_ID"),
    THEME_PACK_UNKNOWN_ID("THEME_PACK_UNKNOWN_ID"),
    FLOOR_MISSING_THEME_PACK("FLOOR_MISSING_THEME_PACK"),
    FLOOR_DUPLICATE_THEME_PACK("FLOOR_DUPLICATE_THEME_PACK"),
    START_BUFF_UNKNOWN_ID("START_BUFF_UNKNOWN_ID");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
